### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by terrylinooo** [hank7444/DesignPatternPHP#1]
依賴注入的概念因為我英文很兩光
有看沒有懂，不知道作者有沒有白話的講解方式

http://fabien.potencier.org/what-is-dependency-injection.html

**Comment by hank7444** [comment]
@terrylinooo 
可以看看這篇: [https://github.com/android-cn/blog/tree/master/java/dependency-injection](https://github.com/android-cn/blog/tree/master/java/dependency-injection)
